#!/bin/bash
# if [  -d "~/.config/nvim/" ]; then
#   mkdir ~/.config/nvim/
# fi
# if [  -d "~/.config/nvim/lua" ]; then
#   mkdir ~/.config/nvim/lua
# fi
cp init.lua ~/.config/nvim/init.lua
cp plugins.lua ~/.config/nvim/lua/plugins.lua