#!/bin/bash
if [ ! -d "$HOME/.config/nvim" ]
  then
    echo "Directory $HOME/.config/nvim does not exists."
    echo "Create $HOME/.config/nvim."
    mkdir $HOME/.config/nvim/
  fi

if [ ! -d "$HOME/.config/nvim/lua" ]
  then
    echo "Directory $HOME/.config/nvim/lua does not exists."
    echo "Create $HOME/.config/nvim/lua."
    mkdir $HOME/.config/nvim/lua
  fi
cp myinit.lua $HOME/.config/nvim/init.lua
cp myplugins.lua $HOME/.config/nvim/lua/plugins.lua
cp -r config $HOME/.config/nvim/lua/
cp .inputrc $HOME/.inputrc